const villaPlayerData = [
    {
        playerId: 1,
        playerPosition: "Goalkeeper",
        playerCountry: "sweden",
        playerImage: require("./olsen.png"),
        playerName: "Robin Olsen ",
      },
      {
        playerId: 2,
        playerPosition: "Goalkeeper",
        playerCountry: "Argentina",
        playerImage: require("./martinez.png"),
        playerName: "Emiliano Martinez",
      },
      {
        playerId: 3,
        playerPosition: "Goalkeeper",
        playerCountry: "Finland",
        playerImage: require("./sinisalo.png"),
        playerName: "Viljami Sinisalo",
      },
      {
        playerId: 4,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./young.png"),
        playerName: "Ashley Young",
      },
      {
        playerId: 5,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./mings.png"),
        playerName: "Tyrone Mings",
      },
      {
        playerId: 6,
        playerPosition: "Defender",
        playerCountry: "Poland",
        playerImage: require("./cash.png"),
        playerName: "Matty Cash",
      },
      {
        playerId: 7,
        playerPosition: "Defender",
        playerCountry: "France",
        playerImage: require("./digne.png"),
        playerName: "Lucas Digne",
      },
      {
        playerId: 8,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./chambers.png"),
        playerName: "Calum Chambers",
      },
      {
        playerId: 9,
        playerPosition: "Defender",
        playerCountry: "Netherlands",
        playerImage: require("./swinkels.png"),
        playerName: "Sil Swinkels",
      },
      {
        playerId: 10,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./konsa.png"),
        playerName: "Ezri Konsa",
      },
      {
        playerId: 11,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./hause.png"),
        playerName: "Kortney Hause",
      },
      {
        playerId: 12,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./ireogbunam.png"),
        playerName: "Tim Iroegbunam",
      },
      {
        playerId: 13,
        playerPosition: "Midfielder",
        playerCountry: "Brazil",
        playerImage: require("./coutinho.png"),
        playerName: "Philip Coutinho",
      },
      {
        playerId: 14,
        playerPosition: "Midfielder",
        playerCountry: "zimbabwe",
        playerImage: require("./nakamba.png"),
        playerName: "Marvelous Nakamba",
      },
      {
        playerId: 15,
        playerPosition: "Midfielder",
        playerCountry: "Brazil",
        playerImage: require("./luiz.png"),
        playerName: "Douglas Luiz",
      },
      {
        playerId: 16,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./lindley.png"),
        playerName: "Hayden Lindley",
      },
      {
        playerId: 17,
        playerPosition: "Midfielder",
        playerCountry: "France",
        playerImage: require("./sanson.png"),
        playerName: "Morgan Sanson",
      },
      {
        playerId: 18,
        playerPosition: "Midfielder",
        playerCountry: "Argenntina",
        playerImage: require("./buendia.png"),
        playerName: "Emiliano Buendia",
      },
      {
        playerId:19,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./ramsey.png"),
        playerName: "Jacob Ramsey",
      },
      {
        playerId: 20,
        playerPosition: "Midfielder",
        playerCountry: "Netherlands",
        playerImage: require("./bogarde.png"),
        playerName: "Lamare Borgarde",
      },
      {
        playerId: 21,
        playerPosition: "Midfielder",
        playerCountry: "Scotland",
        playerImage: require("./macginn.png"),
        playerName: "John McGinn",
      },
      {
        playerId: 22,
        playerPosition: "Midfielder",
        playerCountry: "Jamaica",
        playerImage: require("./bailey.png"),
        playerName: "Leon Bailey",
      },
      {
        playerId: 23,
        playerPosition: "MidFielder",
        playerCountry: "England",
        playerImage: require("./chukwuemeka.png"),
        playerName: "Carney Chukwuemeka",
      },
      {
        playerId: 24,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./ings.png"),
        playerName: "Danny Ings",
      },
      {
        playerId: 25,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./watkins.png"),
        playerName: "Ollie Watkins",
      },
      {
        playerId: 26,
        playerPosition: "Attacker",
        playerCountry: "Burkina Faso",
        playerImage: require("./traore.png"),
        playerName: "Bertrand Traore",
      },

]
export default villaPlayerData