const liverpoolPlayerData = [
  {
    playerId: 1,
    playerPosition: "Goalkeeper",
    playerCountry: "Spain",
    playerImage: require("./adrian.png"),
    playerName: "Adrian",
  },
  {
    playerId: 2,
    playerPosition: "Goalkeeper",
    playerCountry: " Ireland",
    playerImage: require("./kelleher.png"),
    playerName: "Caoimhin Kelleher",
  },
  {
    playerId: 3,
    playerPosition: "Goalkeeper",
    playerCountry: " Germany",
    playerImage: require("./karius.png"),
    playerName: "Loris Karius",
  },
  {
    playerId: 4,
    playerPosition: "Goalkeeper",
    playerCountry: " Brazil",
    playerImage: require("./marcelo.png"),
    playerName: "Marcelo",
  },
  {
    playerId: 5,
    playerPosition: "Goalkeeper",
    playerCountry: " Brazil",
    playerImage: require("./becker.png"),
    playerName: "Allison Becker",
  },
  {
    playerId: 6,
    playerPosition: "Goalkeeper",
    playerCountry: "England ",
    playerImage: require("./davis.png"),
    playerName: "Harvey Davies",
  },
  {
    playerId: 7,
    playerPosition: "Defender",
    playerCountry: "Cameroon ",
    playerImage: require("./matip.png"),
    playerName: "Joel Matip",
  },
  {
    playerId: 8,
    playerPosition: "Defender",
    playerCountry: " England",
    playerImage: require("./gomez.png"),
    playerName: "Joe Gomez",
  },
  {
    playerId:9,
    playerPosition: "Defender",
    playerCountry: " Netherlands",
    playerImage: require("./vanDijk.png"),
    playerName: " Virgil van Dijk",
  },
  {
    playerId: 10,
    playerPosition: "Defender",
    playerCountry: "Greece ",
    playerImage: require("./tsimikas.png"),
    playerName: "Costantinos Tsimikas",
  },
  {
    playerId: 11,
    playerPosition: "Defender",
    playerCountry: " England",
    playerImage: require("./williams.png"),
    playerName: "Rhys Williams",
  },
  {
    playerId: 12,
    playerPosition: "Defender",
    playerCountry: " Scotland",
    playerImage: require("./robertson.png"),
    playerName: "Andrew Robertson",
  },
  {
    playerId: 13,
    playerPosition: "Defender",
    playerCountry: "England ",
    playerImage: require("./alexanderArnold.png"),
    playerName: " Trent Alexander-Arnold",
  },
  {
    playerId: 14,
    playerPosition: "Midfielder",
    playerCountry: "England ",
    playerImage: require("./milner.png"),
    playerName: "James Milner",
  },
  {
    playerId: 15,
    playerPosition: "Midfielder",
    playerCountry: "England ",
    playerImage: require("./chamerlain.png"),
    playerName: "Alex Oxlade-Chamberlain",
  },
  {
    playerId: 16,
    playerPosition: "Midfielder",
    playerCountry: " Colombia",
    playerImage: require("./diaz.png"),
    playerName: "Luis Diaz",
  },
  {
    playerId: 17,
    playerPosition: "Midfielder",
    playerCountry: " England",
    playerImage: require("./clarkson.png"),
    playerName: "Leighton Clarkson",
  },
  {
    playerId: 18,
    playerPosition: "Midfielder",
    playerCountry: " England",
    playerImage: require("./henderson.png"),
    playerName: "Jordan Henderson",
  },
  {
    playerId: 19,
    playerPosition: "Midfielder",
    playerCountry: "Brazil ",
    playerImage: require("./fabinho.png"),
    playerName: "Fabinho",
  },
  {
    playerId: 20,
    playerPosition: "Midfielder",
    playerCountry: " England ",
    playerImage: require("./jones.png"),
    playerName: "Curtis Jones",
  },
  {
    playerId: 21,
    playerPosition: "Midfielder",
    playerCountry: "England ",
    playerImage: require("./morton.png"),
    playerName: "Tyler Morton",
  },
  {
    playerId: 22,
    playerPosition: "Midfielder",
    playerCountry: "Spain ",
    playerImage: require("./alcanara.png"),
    playerName: "Thiago Alcantara",
  },
  {
    playerId: 23,
    playerPosition: "Midfielder",
    playerCountry: "Guinea ",
    playerImage: require("./keita.png"),
    playerName: "Naby Keita",
  },
  {
    playerId: 24,
    playerPosition: "Midfielder",
    playerCountry: " England",
    playerImage: require("./elliott.png"),
    playerName: "Harvey Elliott",
  },
  {
    playerId: 25,
    playerPosition: "Attacker",
    playerCountry: " Brazil",
    playerImage: require("./firmino.png"),
    playerName: "Roberto Firmino",
  },
  {
    playerId: 26,
    playerPosition: "Attacker",
    playerCountry: "Japan ",
    playerImage: require("./minamino.png"),
    playerName: "Takumi Minamino",
  },
  {
    playerId: 27,
    playerPosition: "Attacker",
    playerCountry: "Egypt ",
    playerImage: require("./salah.png"),
    playerName: "Mohammed Salah",
  },
  {
    playerId: 28,
    playerPosition: "Attacker",
    playerCountry: " Belgium",
    playerImage: require("./origi.png"),
    playerName: "Divork Origi",
  },
  {
    playerId: 29,
    playerPosition: "Attacker",
    playerCountry: " Senegal",
    playerImage: require("./mane.png"),
    playerName: "Sadio Mane",
  },
  {
    playerId: 30,
    playerPosition: "Attacker",
    playerCountry: "Portugal ",
    playerImage: require("./jota.png"),
    playerName: "Diogo Jota",
  },
];
export default liverpoolPlayerData;
