const arsenalPlayerData = [
  {
    playerName: "Cedric Soares",
    playerPosition: "Defender",
    playerCountry: "portugal ",
    playerImage: require("./Cedric.png"),
    playerId: 1,
  },
  {
    playerName: "Mohammed Elneny",
    playerPosition: "MidFielder",
    playerCountry: "Egypt",
    playerImage: require("./elneny.png"),
    playerId: 2,
  },
  {
    playerName: "Gabriel Magalhães",
    playerPosition: "Defender",
    playerCountry: "Brazil",
    playerImage: require("./gabriel.png"),
    playerId: 3,
  },
  {
    playerName: "Rob Holding",
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./holding.png"),
    playerId: 4,
  },
  {
    playerId: 5,
    playerName: "Alexander Lacazette",
    playerPosition: "Attacker",
    playerCountry: "France",
    playerImage: require("./lacazette.png"),
  },
  {
    playerId: 6,
    playerName: "Bernd Leno",
    playerPosition: "GoalKeeper",
    playerCountry: "Germany",
    playerImage: require("./leno.png"),
  },
  {
    playerId: 7,
    playerName: "Albert Sambi Lokonga",
    playerPosition: "Midfielder ",
    playerCountry: "Belgium ",
    playerImage: require("./lokonga.png"),
  },
  {
    playerId: 8,
    playerName: "Gabriel Martinelli",
    playerPosition: "Attacker",
    playerCountry: "Brazil",
    playerImage: require("./martinelli.png"),
  },
  {
    playerId: 9,
    playerName: "Edward Nketiah",
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./nketiah.png"),
  },
  {
    playerId: 10,
    playerName: "Martin Ødegaard",
    playerPosition: "MidFielder",
    playerCountry: "Norway",
    playerImage: require("./odegaard.png"),
  },
  {
    playerId: 11,
    playerName: "Thomas Partey",
    playerPosition: "Midfielder",
    playerCountry: "Ghana",
    playerImage: require("./partey.png"),
  },
  {
    playerId: 12,
    playerName: "Nicholas  Pépé",
    playerPosition: "Attacker",
    playerCountry: "Ivory Coast",
    playerImage: require("./partey.png"),
  },
  {
    playerId: 13,
    playerName: "Aaron Ramsdale",
    playerPosition: "Goalkeeper",
    playerCountry: "England",
    playerImage: require("./Ramsdale.png"),
  },
  {
    playerId: 14,
    playerName: "Bukayo saka",
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./saka.png"),
  },
  {
    playerId: 15,
    playerName: "Emile Smith Rowe",
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./smith-rowe.png"),
  },
  {
    playerId: 16,
    playerName: "Nuno Tavares",
    playerPosition: "Defender",
    playerCountry: "Portugal",
    playerImage: require("./tavares.png"),
  },
  {
    playerId: 17,
    playerName: "Takehiro Tomiyasu",
    playerPosition: "Defender",
    playerCountry: "Japan",
    playerImage: require("./tomiyasu.png"),
  },
  {
    playerId: 18,
    playerName: "Ben White",
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./white.png"),
  },
  {
    playerId: 19,
    playerName: "Granit Xhaka",
    playerPosition: "Midfielder",
    playerCountry: "Switzerland",
    playerImage: require("./xhaka.png"),
  },
  {
    playerId: 20,
    playerName: "Kieran Tierney",
    playerPosition: "Defender",
    playerCountry: "Scotland",
    playerImage: require("./tierney.png"),
  },
];

export default arsenalPlayerData