const tottenhamPlayerData = [
    {
        playerId: 1,
        playerPosition: "Goalkeeper",
        playerCountry: "France ",
        playerImage: require("./lloris.png"),
        playerName: "Hugo LLoris",
      },
      {
        playerId: 2,
        playerPosition: "Goalkeeper",
        playerCountry: "Italy",
        playerImage: require("./gollini.png"),
        playerName: "Pierluigi Gollini",
      },
      {
        playerId: 3,
        playerPosition: "Goalkeeper",
        playerCountry: "England ",
        playerImage: require("./austin.png"),
        playerName: "Brandon Austin",
      },
      {
        playerId: 4,
        playerPosition: "Defender",
        playerCountry: "Wales",
        playerImage: require("./davies.png"),
        playerName: "Ben Davies",
      },
      {
        playerId: 5,
        playerPosition: "Defender",
        playerCountry: "Wales",
        playerImage: require("./rodon.png"),
        playerName: "Joe Rodon",
      },
      {
        playerId: 6,
        playerPosition: "Defender",
        playerCountry: "Brazil",
        playerImage: require("./royal.png"),
        playerName: "Emerson Royal",
      },   {
        playerId:7,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./walcot.png"),
        playerName: "Malachi Walcott",
      },
      {
        playerId:8,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./dier.png"),
        playerName: "Eric Dier",
      },
      {
        playerId: 9,
        playerPosition: "Defender",
        playerCountry: "Spain",
        playerImage: require("./reguilon.png"),
        playerName: "Sergio Reguilon",
      },
      {
        playerId: 10,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./tanganga.png"),
        playerName: "Japhet Tanganga",
      },
      {
        playerId: 11,
        playerPosition: "Defender",
        playerCountry: "Colombia",
        playerImage: require("./sanchez.png"),
        playerName: "Davinson Sanchez",
      },
      {
        playerId: 12,
        playerPosition: "Defender",
        playerCountry: "Argentina",
        playerImage: require("./romero.png"),
        playerName: "Cristian Romero",
      },
      {
        playerId: 13,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./lyons-foster.png"),
        playerName: "Brookly Lyons-Foster",
      },

      
      {
        playerId: 14,
        playerPosition: "Midfielder",
        playerCountry: "Ireland",
        playerImage: require("./doherty.png"),
        playerName: "Matt Doherty ",
      },
      {
        playerId: 15,
        playerPosition: "Midfielder",
        playerCountry: "Uruguay",
        playerImage: require("./bentancur.png"),
        playerName: "Rodrigo Bentancur",
      },
      {
        playerId: 16,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./white.png"),
        playerName: "Harvey White",
      },
      {
        playerId:17,
        playerPosition: "Midfielder",
        playerCountry: "Denmark",
        playerImage: require("./hoijbjerg.png"),
        playerName: "Pierre-Emile Hojbjerg",
      },
      {
        playerId: 18,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./sessegnon.png"),
        playerName: "Ryan Sessegnon",
      },
      {
        playerId: 19,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./devine.png"),
        playerName: "Alfie Devine",
      },
      {
        playerId: 20,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./skipp.png"),
        playerName: "Oliver Skipp",
      },
      {
        playerId: 21,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./winks.png"),
        playerName: "Harry Winks",
      },
      {
        playerId: 22,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./kane.png"),
        playerName: "Harry Kane",
      },
      {
        playerId: 23,
        playerPosition: "Attacker",
        playerCountry: "Brazil",
        playerImage: require("./moura.png"),
        playerName: "Lucas Moura",
      },
      {
        playerId: 24,
        playerPosition: "Attacker",
        playerCountry: "South Korea",
        playerImage: require("./son.png"),
        playerName: "Heung-Min son",
      },
      {
        playerId: 25,
        playerPosition: "Attacker",
        playerCountry: "Netherlands",
        playerImage: require("./bergwijn.png"),
        playerName: "Steven Bergwijn",
      },
      {
        playerId: 26,
        playerPosition: "Attacker",
        playerCountry: "Sweden",
        playerImage: require("./kulusevski.png"),
        playerName: "Dejan Kulusevski",
      },
      {
        playerId: 27,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./scarlet.png"),
        playerName: "Dane Scarlet",
      },
]
export default tottenhamPlayerData