const newCastlePlayerData = [
  {
    playerId: 1,
    playerPosition: "Goalkeeper",
    playerCountry: "Slovakia",
    playerImage: require("./dubravka.png"),
    playerName: "Martin Dubravka",
  },
  {
    playerId: 2,
    playerPosition: "Goalkeeper",
    playerCountry: "England",
    playerImage: require("./darlow.png"),
    playerName: "Karl Darlow",
  },
  {
    playerId: 3,
    playerPosition: "Goalkeeper",
    playerCountry: "England",
    playerImage: require("./gillespie.png"),
    playerName: "Mark Gillespie",
  },
  {
    playerId: 4,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./burn.png"),
    playerName: "Daniel Burn",
  },
  {
    playerId: 5,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./lascelles.png"),
    playerName: "Jamaal Lascelles",
  },
  {
    playerId: 6,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./murphy.png"),
    playerName: "Jacob Murphy",
  },
  {
    playerId: 7,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./trippier.png"),
    playerName: "Kieran Tripier",
  },
  {
    playerId: 8,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./targett.png"),
    playerName: "Matt Target",
  },

  {
    playerId: 9,
    playerPosition: "Defender",
    playerCountry: "Argentina",
    playerImage: require("./fernandez.png"),
    playerName: "Fredrico Fernandez",
  },
  {
    playerId: 10,
    playerPosition: "Defender",
    playerCountry: "Sweden",
    playerImage: require("./krafth.png"),
    playerName: "Emil Krafth",
  },
  {
    playerId: 11,
    playerPosition: "Defender",
    playerCountry: "Wales",
    playerImage: require("./dummett.png"),
    playerName: "Paul Dummet",
  },
  {
    playerId: 12,
    playerPosition: "Defender",
    playerCountry: "Scotland",
    playerImage: require("./ritchie.png"),
    playerName: "Matt Ritchie",
  },
  {
    playerId: 13,
    playerPosition: "Defender",
    playerCountry: "Switzerland",
    playerImage: require("./schar.png"),
    playerName: "Fabian Schar",
  },
  {
    playerId: 14,
    playerPosition: "Defender",
    playerCountry: "Ireland",
    playerImage: require("./clark.png"),
    playerName: "Ciaran Clark",
  },
  {
    playerId: 15,
    playerPosition: "Defender",
    playerCountry: "Spain",
    playerImage: require("./maquillo.png"),
    playerName: "Janvier Manquillo",
  },
  {
    playerId: 16,
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./shelvey.png"),
    playerName: "Jonjo Shelvey",
  },
  {
    playerId: 17,
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./willock.png"),
    playerName: "Joseph Willock",
  },
  {
    playerId: 18,
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./longstaff.png"),
    playerName: "Sean Longstaff",
  },
  {
    playerId: 19,
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./hayden.png"),
    playerName: "Isaac Hayden",
  },
  {
    playerId: 20,
    playerPosition: "Midfielder",
    playerCountry: "Brazil",
    playerImage: require("./joelinton.png"),
    playerName: "Joelinton",
  },
  {
    playerId: 21,
    playerPosition: "Midfielder",
    playerCountry: "Brazil",
    playerImage: require("./guimaraes.png"),
    playerName: "Bruno Guimaraes",
  },
  {
    playerId: 22,
    playerPosition: "Attaccker",
    playerCountry: "England",
    playerImage: require("./wilson.png"),
    playerName: "Callum Wilson",
  },
  {
    playerId: 23,
    playerPosition: "Attaccker",
    playerCountry: "England",
    playerImage: require("./gayle.png"),
    playerName: "Dwight Gayle",
  },
  {
    playerId: 24,
    playerPosition: "Attaccker",
    playerCountry: "New Zealand",
    playerImage: require("./wood.png"),
    playerName: "Chris Wood",
  },
  {
    playerId: 25,
    playerPosition: "Attaccker",
    playerCountry: "France ",
    playerImage: require("./saint-maximin.png"),
    playerName: "Allan Saint-Maximine",
  },
  {
    playerId: 26,
    playerPosition: "Attaccker",
    playerCountry: "Scotland",
    playerImage: require("./fraser.png"),
    playerName: "Ryan Fraser",
  },
  {
    playerId: 27,
    playerPosition: "Attaccker",
    playerCountry: "Mexico",
    playerImage: require("./munoz.png"),
    playerName: "Santiago Munoz",
  },
];
export default newCastlePlayerData;
