const westhamPlayerData = [
    {
        playerId: 2,
        playerPosition: "Goalkeeper",
        playerCountry: "England",
        playerImage: require("./martin.png"),
        playerName: "David Martin",
      },
      {
        playerId: 3,
        playerPosition: "Goalkeeper",
        playerCountry: "France",
        playerImage: require("./areola.png"),
        playerName: "Alphonse Areola",
      },
      {
        playerId: 4,
        playerPosition: "Goalkeeper",
        playerCountry: "Poland",
        playerImage: require("./fabianski.png"),
        playerName: "Lukasz Fabianski",
      },
      {
        playerId: 1,
        playerPosition: "Goalkeeper",
        playerCountry: "Ireland",
        playerImage: require("./randolph.png"),
        playerName: "Darren Randolph",
      },
      {
        playerId: 5,
        playerPosition: "Defender",
        playerCountry: "Italy",
        playerImage: require("./ogbonna.png"),
        playerName: "Angelo Ogbonna",
      },
      {
        playerId: 6,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./fredericks.png"),
        playerName: "Ryan Fredricks",
      },
      {
        playerId: 7,
        playerPosition: "Defender",
        playerCountry: "DR Congo",
        playerImage: require("./masuakku.png"),
        playerName: "Arthur Masuaku",
      },
      {
        playerId: 8,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./alese.png"),
        playerName: "Ajibola Alese",
      },
      {
        playerId: 9,
        playerPosition: "Defender",
        playerCountry: "",
        playerImage: require("./baptiste.png"),
        playerName: "Jamal Baptiste",
      },
      {
        playerId: 10,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./cresswell.png"),
        playerName: "Aaron Cresswell",
      },
      {
        playerId: 11,
        playerPosition: "Defender",
        playerCountry: "France",
        playerImage: require("./zouma.png"),
        playerName: "Kurt Zouma",
      },
      {
        playerId: 12,
        playerPosition: "Defender",
        playerCountry: "France",
        playerImage: require("./diop.png"),
        playerName: "Issa Diop",
      },
      {
        playerId: 13,
        playerPosition: "Defender",
        playerCountry: "england",
        playerImage: require("./longelo.png"),
        playerName: "Emmannuel Longelo",
      },
      {
        playerId: 14,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./dawson.png"),
        playerName: "Craig Dawson",
      },   {
        playerId: 15,
        playerPosition: "Defender",
        playerCountry: "Czech Republic",
        playerImage: require("./coufal.png"),
        playerName: "Vladimir Coufal",
      },
      {
        playerId: 16,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./johnson.png"),
        playerName: "Ben Johnson",
      },
      {
        playerId: 17,
        playerPosition: "Defender",
        playerCountry: "Scotland",
        playerImage: require("./ashby.png"),
        playerName: "Harrison Ashby",
      },

      {
        playerId: 18,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./noble.png"),
        playerName: "Mark Noble",
      },
      {
        playerId: 19,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./rice.png"),
        playerName: "Declan Rice",
      },
      {
        playerId: 20,
        playerPosition: "Midfielder",
        playerCountry: "Argentina",
        playerImage: require("./lanzini.png"),
        playerName: "Manuel Lanzini",
      },
      {
        playerId: 21,
        playerPosition: "Midfielder",
        playerCountry: "Czech Republic",
        playerImage: require("./kral.png"),
        playerName: "Alex Kral",
      },
      {
        playerId: 22,
        playerPosition: "Midfielder",
        playerCountry: "Czech Republic",
        playerImage: require("./soucek.png"),
        playerName: "Tomas Soucek",
      },

      {
        playerId: 23,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./bowen.png"),
        playerName: "Jarod Bowen",
      },
      {
        playerId: 24,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./chesters.png"),
        playerName: "Daniel Chesters",
      },
      {
        playerId: 25,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./oko-flex.png"),
        playerName: "Armstrong Oko-Flex",
      },
      {
        playerId: 26,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./perkins.png"),
        playerName: "Sonny Perkins",
      },
      {
        playerId: 27,
        playerPosition: "Attacker",
        playerCountry: "Ukraine",
        playerImage: require("./yarmolenko.png"),
        playerName: "Andriy Yarmolenko",
      },
      {
        playerId: 28,
        playerPosition: "Attacker",
        playerCountry: "Jamaica",
        playerImage: require("./antonio.png"),
        playerName: "Michail Antonio",
      },
      {
        playerId: 29,
        playerPosition: "Attacker",
        playerCountry: "Algeria",
        playerImage: require("./benrahma.png"),
        playerName: "Said Benrahma",
      },
      {
        playerId: 30,
        playerPosition: "Attacker",
        playerCountry: "Spain",
        playerImage: require("./fornals.png"),
        playerName: "Pablo Fornals",
      },
]
export default westhamPlayerData