const southamptonPlayerData = [
    {
        playerId: 1,
        playerPosition: "Goalkeeper",
        playerCountry: "Argentina",
        playerImage: require("./caballero.png"),
        playerName: "Wilfredo Caballero",
      },
      {
        playerId: 2,
        playerPosition: "Goalkeeper",
        playerCountry: "England",
        playerImage: require("./forster.png"),
        playerName: "Fraser Forster",
      },
      {
        playerId: 3,
        playerPosition: "Goalkeeper",
        playerCountry: "England",
        playerImage: require("./lewis.png"),
        playerName: "Harry Lewis",
      },
      {
        playerId: 4,
        playerPosition: "Goalkeeper",
        playerCountry: "England",
        playerImage: require("./mccarthy.png"),
        playerName: "Alex McCarthy",
      },
      {
        playerId: 5,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./stephens.png"),
        playerName: "Jack Stephens",
      },
      {
        playerId: 6,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./walker-peters.png"),
        playerName: "Kyle Walker-Peters",
      },
      {
        playerId: 7,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./livramento.png"),
        playerName: " Valentino Livramento",
      },
      {
        playerId: 8,
        playerPosition: "Defender",
        playerCountry: "Ghana",
        playerImage: require("./salisu.png"),
        playerName: "Mohammed Salisu",
      },
      {
        playerId: 9,
        playerPosition: "Defender",
        playerCountry: "Poland",
        playerImage: require("./bednarek.png"),
        playerName: "Jan Bednarek",
      },
      {
        playerId: 10,
        playerPosition: "Defender",
        playerCountry: "France",
        playerImage: require("./valery.png"),
        playerName: "Yan Valery",
      },
      {
        playerId: 11,
        playerPosition: "Defender",
        playerCountry: "Brazil",
        playerImage: require("./lyanco.png"),
        playerName: "Lyanco",
      },
      {
        playerId: 12,
        playerPosition: "Defender",
        playerCountry: "France",
        playerImage: require("./perraud.png"),
        playerName: "Romain Perraud",
      },
      {
        playerId: 13,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./walcot.png"),
        playerName: "Theo Walcot",
      },
      {
        playerId: 14,
        playerPosition: "Midfielder",
        playerCountry: "Scotland",
        playerImage: require("./armstrong.png"),
        playerName: "Stuart Armstrong",
      },
      {
        playerId: 15,
        playerPosition: "Midfielder",
        playerCountry: "Ireland",
        playerImage: require("./smallbone.png"),
        playerName: "William Smallbone",
      },
      {
        playerId: 16,
        playerPosition: "Midfielder",
        playerCountry: "France",
        playerImage: require("./diallo.png"),
        playerName: "Ibrahima Diallo",
      },
      {
        playerId: 17,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./redmond.png"),
        playerName: "Nathan Redmond",
      },
      {
        playerId: 18,
        playerPosition: "Midfielder",
        playerCountry: "Norway",
        playerImage: require("./elyounoussi.png"),
        playerName: "Mohamed Elyounoussi",
      },
      {
        playerId: 19,
        playerPosition: "Midfielder",
        playerCountry: "Mali",
        playerImage: require("./djenepo.png"),
        playerName: "Mousa Djenepo",
      },
      {
        playerId: 20,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./chauke.png"),
        playerName: "Kgaogelo Chauke",
      },
      {
        playerId: 21,
        playerPosition: "Midfielder",
        playerCountry: "Spain",
        playerImage: require("./romeu.png"),
        playerName: "Oriol Romeu",
      },
      {
        playerId: 22,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./ward-prowse.png"),
        playerName: "James Ward-Prowse",
      },
      {
        playerId: 23,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./tella.png"),
        playerName: "Nathan Tella",
      },
      {
        playerId: 24,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./small.png"),
        playerName: "Thiery Small",
      },
      {
        playerId: 25,
        playerPosition: "Attacker",
        playerCountry: "Ireland",
        playerImage: require("./long.png"),
        playerName: "Shane Long",
      },
      {
        playerId: 26,
        playerPosition: "Attacker",
        playerCountry: "Albania",
        playerImage: require("./broja.png"),
        playerName: "Armando Broja",
      },
      {
        playerId: 27,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./adamArmstong.png"),
        playerName: "Adam Arstrong",
      },
      {
        playerId: 28,
        playerPosition: "Attacker",
        playerCountry: "Scotland",
        playerImage: require("./adams.png"),
        playerName: "Che Adams ",
      },
]
export default southamptonPlayerData