const manCityPlayerData = [
  {
    playerId: 1,
    playerPosition: "Goalkeeper",
    playerCountry: "England",
    playerImage: require("./carson.png"),
    playerName: "Scot Carson",
  },
  {
    playerId: 2,
    playerPosition: "Goalkeeper",
    playerCountry: "Brazil",
    playerImage: require("./ederson.png"),
    playerName: "Ederson Moraes",
  },
  {
    playerId: 3,
    playerPosition: "Goalkeeper",
    playerCountry: "USA",
    playerImage: require("./steffen.png"),
    playerName: "Zack Steffen",
  },
  {
    playerId: 4,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./walker.png"),
    playerName: "Kyle Walker",
  },
  {
    playerId: 5,
    playerPosition: "Defender",
    playerCountry: "Portugal",
    playerImage: require("./cancello.png"),
    playerName: "Joao Cancello",
  },
  {
    playerId: 6,
    playerPosition: "Defender",
    playerCountry: "Portugal",
    playerImage: require("./dias.png"),
    playerName: "Ruben Dias",
  },
  {
    playerId: 7,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./stones.png"),
    playerName: "John Stones",
  },
  {
    playerId: 8,
    playerPosition: "Defender",
    playerCountry: "Spain",
    playerImage: require("./laporte.png"),
    playerName: "Aymeric Laporte",
  },
  {
    playerId: 9,
    playerPosition: "Defender",
    playerCountry: "Ukraine",
    playerImage: require("./zinchenko.png"),
    playerName: "Oleksandr Zinchenko",
  },
  {
    playerId: 10,
    playerPosition: "Defender",
    playerCountry: "France ",
    playerImage: require("./mendy.png"),
    playerName: "Benjamin Mendy",
  },
  {
    playerId: 11,
    playerPosition: "Defender",
    playerCountry: "Netherlands",
    playerImage: require("./ake.png"),
    playerName: "Nathan Ake",
  },
  {
    playerId: 12,
    playerPosition: "Midfielder",
    playerCountry: "Brazil",
    playerImage: require("./fernandinho.png"),
    playerName: "Fernandinho",
  },
  {
    playerId: 13,
    playerPosition: "Midfielder",
    playerCountry: "Portugal",
    playerImage: require("./bernado.png"),
    playerName: "Bernado Silva",
  },
  {
    playerId: 14,
    playerPosition: "Midfielder",
    playerCountry: "Belgium",
    playerImage: require("./lavia.png"),
    playerName: "Romeo Lavia",
  },
  {
    playerId: 15,
    playerPosition: "Midfielder",
    playerCountry: "Belgium",
    playerImage: require("./deBruyne.png"),
    playerName: "Kevin de Bruyne",
  },
  {
    playerId: 12,
    playerPosition: "Midfielder",
    playerCountry: "Spain",
    playerImage: require("./rodri.png"),
    playerName: "Rodri",
  },
  {
    playerId: 12,
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./palmer.png"),
    playerName: "Cole Palmer",
  },
  {
    playerId: 12,
    playerPosition: "Midfielder",
    playerCountry: "Germany",
    playerImage: require("./gundogan.png"),
    playerName: "Ilkay Gundogan",
  },
  {
    playerId: 13,
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./sterlin.png"),
    playerName: "Raheem Sterlin",
  },
  {
    playerId: 14,
    playerPosition: "Attacker",
    playerCountry: "Brazil",
    playerImage: require("./jesus.png"),
    playerName: "Gabriel Jesus",
  },
  {
    playerId: 15,
    playerPosition: "Attacker",
    playerCountry: "Algeria",
    playerImage: require("./mahrez.png"),
    playerName: "Riyad Mahrez",
  },
  {
    playerId: 16,
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./foden.png"),
    playerName: "Phil Foden",
  },
  {
    playerId: 17,
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./grealish.png"),
    playerName: "Jack Grealish",
  },
];
export default manCityPlayerData;
