const palacePlayerData =[
    {
        playerId: 1,
        playerPosition: "Goalkeeper",
        playerCountry: "England",
        playerImage: require("./butland.png"),
        playerName: "Jack Butland",
      },
      {
        playerId: 2,
        playerPosition: "Goalkeeper",
        playerCountry: "England",
        playerImage: require("./mathews.png"),
        playerName: "Remi Mathews",
      },
      {
        playerId: 3,
        playerPosition: "Goalkeeper",
        playerCountry: "Spain",
        playerImage: require("./guaita.png"),
        playerName: "Vincente Guaita",
      },
      {
        playerId: 4,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./tomkins.png"),
        playerName: "James Tomkins",
      },
      {
        playerId: 5,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./clyne.png"),
        playerName: "Nathan Clyne",
      },
      {
        playerId: 6,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./guehi.png"),
        playerName: "Marc Guehi",
      },
      {
        playerId: 7,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./mitchell.png"),
        playerName: "Tyrick Mitchell",
      },
      {
        playerId:8,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./ward.png"),
        playerName: "Joe Ward",
      },
      {
        playerId: 9,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./ferguson.png"),
        playerName: "Nathan Ferguson",
      },
      {
        playerId: 10,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./kelly.png"),
        playerName: "Martin Kelly",
      },
      {
        playerId: 11,
        playerPosition: "Defender",
        playerCountry: "England",
        playerImage: require("./hannam.png"),
        playerName: "Reece Hannam",
      },
      {
        playerId: 12,
        playerPosition: "Defender",
        playerCountry: "Poland",
        playerImage: require("./jach.png"),
        playerName: "Jaroslaw Jach",
      },
      {
        playerId: 13,
        playerPosition: "Defender",
        playerCountry: "Denmark",
        playerImage: require("./andersen.png"),
        playerName: "Joachim Andersen",
      },
      {
        playerId: 15,
        playerPosition: "Midfielder",
        playerCountry: "Scotland",
        playerImage: require("./mcarthur.png"),
        playerName: "James McAthur",
      },
      {
        playerId: 16,
        playerPosition: "Midfielder",
        playerCountry: "Ghana",
        playerImage: require("./schlupp.png"),
        playerName: "Jeffrey Schlupp",
      },
      {
        playerId: 17,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./eze.png"),
        playerName: "Eberechi Eze",
      },
      {
        playerId: 18,
        playerPosition: "Midfielder",
        playerCountry: "Senegal",
        playerImage: require("./kouyate.png"),
        playerName: "Cheikhou Kouyate",
      },
      {
        playerId: 19,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./hughes.png"),
        playerName: "Will Hughes",
      },
      {
        playerId: 20,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./gallagher.png"),
        playerName: "Connor Gallagher",
      },
      {
        playerId: 21,
        playerPosition: "Midfielder",
        playerCountry: "Serbia",
        playerImage: require("./milvojevic.png"),
        playerName: "Luka Milivojevic",
      },
      {
        playerId: 22,
        playerPosition: "Midfielder",
        playerCountry: "Netherland",
        playerImage: require("./riedewald.png"),
        playerName: "Jairo Riedewald",
      },
      {
        playerId: 23,
        playerPosition: "Midfielder",
        playerCountry: "England",
        playerImage: require("./rak-sakyi.png"),
        playerName: "Jesurun Rak-Sakyi",
      },
      {
        playerId: 24,
        playerPosition: "Attacker",
        playerCountry: "Belgium",
        playerImage: require("./benteke.png"),
        playerName: "Christian Benteke",
      },
      {
        playerId: 25,
        playerPosition: "Attacker",
        playerCountry: "Ghana",
        playerImage: require("./ayew.png"),
        playerName: "Jordan Ayew",
      },
      {
        playerId: 26,
        playerPosition: "Attacker",
        playerCountry: "Ivory Coast",
        playerImage: require("./zaha.png"),
        playerName: "Wilfred Zaha",
      },
      {
        playerId: 27,
        playerPosition: "Attacker",
        playerCountry: "France",
        playerImage: require("./edouard.png"),
        playerName: "Odsonne Edouard",
      },
      {
        playerId: 28,
        playerPosition: "Attacker",
        playerCountry: "France",
        playerImage: require("./mateta.png"),
        playerName: "Jean-Philip Mateta",
      },
      {
        playerId: 29,
        playerPosition: "Attacker",
        playerCountry: "England",
        playerImage: require("./olise.png"),
        playerName: "Michael Olise",
      },

]
export default palacePlayerData