const wolvesplayerData = [
  {
    playerId: 1,
    playerPosition: "Goalkeeper",
    playerCountry: "England",
    playerImage: require("./ruddy.png"),
    playerName: "John Ruddy",
  },
  {
    playerId: 2,
    playerPosition: "Goalkeeper",
    playerCountry: "Portugal",
    playerImage: require("./sa.png"),
    playerName: "Jose Sa",
  },
  {
    playerId: 3,
    playerPosition: "Goalkeeper",
    playerCountry: "Denmark",
    playerImage: require("./sondergaard.png"),
    playerName: "Andreas Sonndergaard",
  },
  {
    playerId: 4,
    playerPosition: "Goalkeeper",
    playerCountry: "England",
    playerImage: require("./storer.png"),
    playerName: "James Storer",
  },
  {
    playerId: 5,
    playerPosition: "Goalkeeper",
    playerCountry: "Montenegro",
    playerImage: require("./sarkic.png"),
    playerName: "Matija Sarkic",
  },
  {
    playerId:6,
    playerPosition: "Defender",
    playerCountry: "Ivory Coast",
    playerImage: require("./boly.png"),
    playerName: "Willy Boly",
  },
  {
    playerId: 7,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./kilman.png"),
    playerName: "Max Kilman",
  },
  {
    playerId: 8,
    playerPosition: "Defender",
    playerCountry: "Colombia",
    playerImage: require("./mosquera.png"),
    playerName: "Yerson Mosquera",
  },
  {
    playerId: 9,
    playerPosition: "Defender",
    playerCountry: "England",
    playerImage: require("./coady.png"),
    playerName: "Conor Coady",
  },
  {
    playerId: 10,
    playerPosition: "Defender",
    playerCountry: "Portugal",
    playerImage: require("./gomes.png"),
    playerName: "Toti Gomes",
  },
  {
    playerId: 11,
    playerPosition: "Defender",
    playerCountry: "Morocco",
    playerImage: require("./saiss.png"),
    playerName: "Romain Saiss",
  },
  {
    playerId: 12,
    playerPosition: "Defender",
    playerCountry: "Spain",
    playerImage: require("./bueno.png"),
    playerName: "Hugo Bueno",
  },
  {
    playerId: 13,
    playerPosition: "Midfielder",
    playerCountry: "Portugal",
    playerImage: require("./moutinho.png"),
    playerName: "Joao Moutinho",
  },
  {
    playerId: 14,
    playerPosition: "Midfielder",
    playerCountry: "Belgium",
    playerImage: require("./dendoncker.png"),
    playerName: "Leander Dendoncker",
  },
  {
    playerId: 15,
    playerPosition: "Midfielder",
    playerCountry: "Portugal",
    playerImage: require("./neto.png"),
    playerName: "Pedro Neto",
  },
  {
    playerId: 16,
    playerPosition: "Midfielder",
    playerCountry: "Netherlands",
    playerImage: require("./hoever.png"),
    playerName: "Ki-Jana Hoever",
  },
  {
    playerId: 17,
    playerPosition: "Midfielder",
    playerCountry: "Brazil",
    playerImage: require("./marcal.png"),
    playerName: "Fernando Marcal",
  },
  {
    playerId: 18,
    playerPosition: "Midfielder",
    playerCountry: "Portugal",
    playerImage: require("./semedo.png"),
    playerName: "Nelson Semedo",
  },
  {
    playerId: 19,
    playerPosition: "Midfielder",
    playerCountry: "Franc",
    playerImage: require("./nouri.png"),
    playerName: "Rayan Ait Nouri",
  },
  {
    playerId: 20,
    playerPosition: "Midfielder",
    playerCountry: "Spain",
    playerImage: require("./jonny.png"),
    playerName: "Jonny",
  },
  {
    playerId: 21,
    playerPosition: "Midfielder",
    playerCountry: "Portugal",
    playerImage: require("./neves.png"),
    playerName: "Ruben Neves",
  },
  {
    playerId: 22,
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./cundle.png"),
    playerName: "Luke Cundle",
  },

  {
    playerId: 23,
    playerPosition: "Attacker",
    playerCountry: "Mexico",
    playerImage: require("./jimenez.png"),
    playerName: "Raul Jimenez",
  },
  {
    playerId: 24,
    playerPosition: "Attacker",
    playerCountry: "South Korea",
    playerImage: require("./hwang.png"),
    playerName: "Hee-chan Hwang",
  },
  {
    playerId: 25,
    playerPosition: "Attacker",
    playerCountry: "Portugal",
    playerImage: require("./trincao.png"),
    playerName: "Trincao",
  },
  {
    playerId: 26 ,
    playerPosition: "Attacker",
    playerCountry: "Portugal",
    playerImage: require("./podence.png"),
    playerName: "Daniel Podence",
  },
  {
    playerId: 27,
    playerPosition: "Attacker",
    playerCountry: "Portugal",
    playerImage: require("./silva.png"),
    playerName: "Fabio Silva",
  },
  {
    playerId: 28,
    playerPosition: "Attacker",
    playerCountry: "Portugal",
    playerImage: require("./chiquinho.png"),
    playerName: "Chiquinho",
  },
];
export default wolvesplayerData;
