const brentfordPlayerData = [
  {
    playerId: 1,
    playerName: "Kristofer Ajer ",
    playerPosition: "Defender",
    playerCountry: "Norway",
    playerImage: require("./ajer.png"),
  },
  {
    playerId: 2,
    playerName: "Jonas Lössl",
    playerPosition: "Goalkeeper",
    playerCountry: "Denmark",
    playerImage: require("./lossl.png"),
  },
  {
    playerId: 3,
    playerName: "Mathew Cox",
    playerPosition: "Goalkeeper",
    playerCountry: "England",
    playerImage: require("./cox.png"),
  },
  {
    playerId: 4,
    playerName: "David Raya",
    playerPosition: "Goalkeeper",
    playerCountry: "Spain",
    playerImage: require("./raya.png"),
  },
  {
    playerId: 5,
    playerName: "Álvaro Fernández",
    playerPosition: "Goalkeeper",
    playerCountry: "Spain",
    playerImage: require("./alvaro-fernandez.png"),
  },
  {
    playerId: 6,
    playerPosition: "Defender",
    playerName: "Pontus Jansson",
    playerCountry: "Sweden",
    playerImage: require("./jansen.png"),
  },
  {
    playerId: 7,
    playerName: "Mathias Jørgensen",
    playerPosition: "Defender",
    playerCountry: "Denmark",
    playerImage: require("./jorgensen.png"),
  },
  {
    playerId: 8,
    playerName: " Julian Jeanvier",
    playerPosition: "Defender",
    playerCountry: "Guinea",
    playerImage: require("./jeanvier.png"),
  },
  {
    playerId: 9,
    playerName: "Fin Stevens",
    playerPosition: "Defender",
    playerCountry: "Wales",
    playerImage: require("./stevens.png"),
  },
  {
    playerId: 10,
    playerName: " Mads Bech",
    playerPosition: "Defender",
    playerCountry: "Denmark",
    playerImage: require("./bech.png"),
  },
  {
    playerId: 11,
    playerName: "Ethan Pinnock",
    playerPosition: "Defender",
    playerCountry: "Jamaica",
    playerImage: require("./pinnock.png"),
  },
  {
    playerId: 12,
    playerName: "Christian Eriksen",
    playerPosition: "Midfielder",
    playerCountry: "Denmark",
    playerImage: require("./eriksen.png"),
  },
  {
    playerId: 13,
    playerName: "Rico Henry",
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./ricoHenry.png"),
  },
  {
    playerId: 14,
    playerName: "Sergi Canos",
    playerPosition: "Midfielder",
    playerCountry: "Spain",
    playerImage: require("./sergiCanos.png"),
  },
  {
    playerId: 15,
    playerName: "Mads Roerslev",
    playerPosition: "Midfielder",
    playerCountry: " Denmark",
    playerImage: require("./madsRoerslev.png"),
  },
  {
    playerId: 16,
    playerName: "Edmond-Paris Maghoma",
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./maghoma.png"),
  },
  {
    playerId: 17,
    playerName: "Christian Nørgaard",
    playerPosition: "Midfielder",
    playerCountry: "Denmark",
    playerImage: require("./norgaard.png"),
  },
  {
    playerId: 18,
    playerName: "Tariqe Fosu",
    playerPosition: "Midfielder",
    playerCountry: "Ghana",
    playerImage: require("./fosu.png"),
  },
  {
    playerId: 19,
    playerName: "Vitaly Janelt",
    playerPosition: "Midfielder",
    playerCountry: "Germany",
    playerImage: require("./vitalyJanelt.png"),
  },
  {
    playerId: 20,
    playerName: "Frank Onyeka",
    playerPosition: "Midfielder",
    playerCountry: "Nigeria",
    playerImage: require("./onyeka.png"),
  },
  {
    playerId: 21,
    playerName: "Myles Peart-Harris",
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./harris.png"),
  },
  {
    playerId: 22,
    playerName: "Saman Ghoddos",
    playerPosition: "Midfielder",
    playerCountry: "Iran",
    playerImage: require("./ghoddos.png"),
  },
  {
    playerId: 23,
    playerName: "Mathia Jensen",
    playerPosition: "Midfielder",
    playerCountry: "Denmark ",
    playerImage: require("./mathiasJensen.png"),
  },
  {
    playerId: 24,
    playerName: "Joshua Dasilva",
    playerPosition: "Midfielder",
    playerCountry: "England",
    playerImage: require("./dasilva.png"),
  },
  {
    playerId: 25,
    playerName: "Shandon Baptiste",
    playerPosition: "Midfielder",
    playerCountry: "Grenada",
    playerImage: require("./baptiste.png"),
  },
  {
    playerId: 26,
    playerName: " Ivan Toney",
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./toney.png"),
  },
  {
    playerId: 27,
    playerName: "Daniel Oyegoke",
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./oyegoke.png"),
  },
  {
    playerId: 28,
    playerName: "Max Haygarth",
    playerPosition: "Attacker",
    playerCountry: "England",
    playerImage: require("./haygarth.png"),
  },
  {
    playerId: 29,
    playerPosition: "Attacker",
    playerCountry: "England",
    playerName: "Nathan Young-Coombes",
    playerImage: require("./young-coombes.png"),
  },
  {
    playerId: 30,
    playerPosition: "Attacker",
    playerCountry: "DR Congo",
    playerName: "Yoane Wissa",
    playerImage: require("./wissa.png"),
  },
  {
    playerId: 31,
    playerPosition: "Attacker",
    playerCountry: "France",
    playerName: "Bryan Mbeumo",
    playerImage: require("./mbuemo.png"),
  },
];

export default brentfordPlayerData;
